### ISSUE TITLE
supporting Graphana 7.5

### ISSUE THREAD

**Issue by M-Shash** [netxms/grafana#15]
I have 2 questions:
1- Is the latest plugin version support Grafana 7.5?
2- what is the supported netxms server version?

**Comment by M-Shash** [comment]
@alkk @zev333 
@2128506 @Sviests 
Sorry for the mentions as I don't know if it correct or no but may you help me to speed it up by telling me where to go or post

**Comment by alkk** [comment]
Latest release of the NetXMS should be supported by this plugin, however we haven't tested grafana 7.5 yet.

**Comment by M-Shash** [comment]
great, may I ask what is the latest tested Grafana version

**Comment by alkk** [comment]
Yes, seems fine.
And latest version of the plugin is signed.
