### ISSUE TITLE
response.headers is not a function

### ISSUE THREAD

**Issue by mhollstein** [netxms/grafana#7]
After upgrade to Grafana 6.7.x the netxms datasource response with
"response.headers is not a function"

NetXMS Datasource is working until Grafana 6.6.2

**Comment by alkk** [comment]
Fixed in d019c1b44d8d722789c7f4118a8e9ea4b135ce15.
It will take to push update to official registry, in a meantime you can upgrade directly from git:

```
grafana-cli plugins uninstall radensolutions-netxms-datasource
cd $GRAFANA_HOME/data/plugins
git clone https://github.com/netxms/grafana.git radensolutions-netxms-datasource
```
