### ISSUE TITLE
unparseable date

### ISSUE THREAD

**Issue by mhollstein** [netxms/grafana#8]
With Grafana >= 6.7.x I'll get an error 46; with Grafana 6.6.2 everything works well.

NetXMS
DCI
Target: netxms
DCI: CPU: usage

Query Inspector result: 

Object
status:500
statusText:"Internal Server Error"
data:Object
description:"Unparseable date: "hu Apr 09 2020 11:10:02 GMT+020""
error:46
message:46

**Comment by alkk** [comment]
Fixed a while ago
